// CALL REQUEST creation
export const CALL_REQUEST_CREATION_REQUESTED =
    'CALL_REQUEST_CREATION_REQUESTED';
export const CALL_REQUEST_CREATION_SUCCESS = 'CALL_REQUEST_CREATION_SUCCESS';
export const CALL_REQUEST_CREATION_FAILED = 'CALL_REQUEST_DELETE_FAILED';

// CALL REQUEST cancel
export const CALL_REQUEST_CANCEL_REQUESTED = 'CALL_REQUEST_CANCEL_REQUESTED';
export const CALL_REQUEST_CANCEL_SUCCESS = 'CALL_REQUEST_CANCEL_SUCCESS';
export const CALL_REQUEST_CANCEL_FAILED = 'CALL_REQUEST_CANCEL_FAILED';

// CALL REQUEST finish
export const CALL_REQUEST_FINISH_REQUESTED = 'CALL_REQUEST_FINISH_REQUESTED';
export const CALL_REQUEST_FINISH_FAILED = 'CALL_REQUEST_FINISH_FAILED';
export const CALL_REQUEST_FINISH_SUCCESS = 'CALL_REQUEST_FINISH_SUCCESS';

// CALL REQUEST refresh
export const CALL_REQUEST_REFRESH_STATE_REQUESTED =
    'CALL_REQUEST_REFRESH_STATE_REQUESTED';
export const CALL_REQUEST_REFRESH_STATE_SUCCESS =
    'CALL_REQUEST_REFRESH_STATE_SUCCESS';
export const CALL_REQUEST_REFRESH_STATE_FAILED =
    'CALL_REQUEST_REFRESH_STATE_FAILED';

// CALL REQUEST polling interval
export const CALL_REQUEST_POLLING_INTERVAL_CREATED = 'CALL_REQUEST_POLLING_INTERVAL_CREATED';
export const CALL_REQUEST_POLLING_INTERVAL_REMOVED = 'CALL_REQUEST_POLLING_INTERVAL_REMOVED';

// CALL fetch
export const CALL_FETCH_REQUESTED = 'CALL_FETCH_REQUESTED';
export const CALL_FETCH_SUCCESS = 'CALL_FETCH_SUCCESS';
export const CALL_FETCH_FAILED = 'CALL_FETCH_FAILED';

// CALL remove
export const CALL_REMOVE_SUCCESS = 'CALL_REMOVE_SUCCESS';

// STORES
export const STORES_FETCH_REQUESTED = 'STORES_FETCH_REQUESTED';
export const STORES_FETCH_SUCCESS = 'STORES_FETCH_SUCCESS';
export const STORES_FETCH_FAILED = 'STORES_FETCH_FAILED';
