// Call Request
export const CALL_REQUEST_CREATION_REQUESTED =
    'CALL_REQUEST_CREATION_REQUESTED';
export const CALL_REQUEST_CREATION_SUCCESS = 'CALL_REQUEST_CREATION_SUCCESS';
export const CALL_REQUEST_CREATION_FAILED = 'CALL_REQUEST_CREATION_FAILED';
